// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PRN231.TrialTest.Library.Models;

public partial class FootballClub
{
    [Key]
    public string FootballClubId { get; set; }

    public string ClubName { get; set; }

    public string ClubShortDescription { get; set; }

    public string SoccerPracticeField { get; set; }

    public string Mascos { get; set; }

    //public virtual ICollection<FootballPlayer> FootballPlayers { get; set; } = new List<FootballPlayer>();
}