// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN231.TrialTest.Library.Models;

public partial class FootballPlayer
{
    public string FootballPlayerId { get; set; }

    public string FullName { get; set; }

    public string Achievements { get; set; }

    public DateTime? Birthday { get; set; }

    public string PlayerExperiences { get; set; }

    public string Nomination { get; set; }

    public string FootballClubId { get; set; }

    public virtual FootballClub FootballClub { get; set; }
}