// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN231.TrialTest.Library.Models;

public partial class PremierLeagueAccount
{
    public int AccId { get; set; }

    public string Password { get; set; }

    public string EmailAddress { get; set; }

    public string Description { get; set; }

    public int? Role { get; set; }
}